app.index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
      template: public/home.html.twig

app.lobby:
  path: /lobby
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: public/lobby.html.twig

app.admin:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: admin/admin.html.twig
